# Generated by Django 4.2.1 on 2023-05-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='usertype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
