# Generated by Django 4.2.1 on 2023-05-26 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_registration_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='usertype',
        ),
    ]
