# Generated by Django 4.2.1 on 2023-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_commonlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopreg',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
