# Generated by Django 4.2.1 on 2023-06-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_registration_status_shopreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonlogin',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
