# Generated by Django 4.2.1 on 2023-06-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_commonlogin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('pdtname', models.CharField(max_length=100, null=True)),
                ('MRP', models.IntegerField(max_length=100, null=True)),
                ('offerprice', models.IntegerField(max_length=100, null=True)),
                ('discription', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
