# Generated by Django 4.2.1 on 2023-06-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shopname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
