# Generated by Django 4.2.1 on 2023-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0010_products_shopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='MRP',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
