# Generated by Django 4.2.1 on 2023-06-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0011_alter_products_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shopid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalapp.shopreg'),
        ),
    ]
