# Generated by Django 4.2.1 on 2023-06-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_products_shopid'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalapp.products')),
                ('shopid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalapp.shopreg')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalapp.registration')),
            ],
        ),
    ]
